### ISSUE TITLE
Bad argument type for built-in operation

### ISSUE THREAD

**Issue by gdude2002** [SunDwarf/Kyoukai#19]
Python: 3.6.0 x64 (Windows)
Kyoukai: 2.0.2 (Latest on PyPi)

```
Traceback (most recent call last):
  File "C:/Users/-gdude2002/WebStormProjects/MysticMinecraft/app.py", line 2, in <module>
    from kyoukai import Kyoukai
  File "C:\Python36\lib\site-packages\kyoukai\__init__.py", line 4, in <module>
    from kyoukai.app import Kyoukai, __version__
  File "C:\Python36\lib\site-packages\kyoukai\app.py", line 9, in <module>
    from asphalt.core import Context, run_application
  File "C:\Python36\lib\site-packages\asphalt\core\__init__.py", line 1, in <module>
    from .component import *
  File "C:\Python36\lib\site-packages\asphalt\core\component.py", line 11, in <module>
    from asphalt.core.context import Context
  File "C:\Python36\lib\site-packages\asphalt\core\context.py", line 10, in <module>
    from asphalt.core.event import Signal, Event
  File "C:\Python36\lib\site-packages\asphalt\core\event.py", line 11, in <module>
    from asyncio_extras.asyncyield import yield_async
  File "C:\Python36\lib\site-packages\asyncio_extras\__init__.py", line 1, in <module>
    from .asyncyield import *  # noqa
  File "C:\Python36\lib\site-packages\asyncio_extras\asyncyield.py", line 3, in <module>
    from async_generator import yield_
  File "C:\Python36\lib\site-packages\async_generator\__init__.py", line 1, in <module>
    from .impl import (
  File "C:\Python36\lib\site-packages\async_generator\impl.py", line 27, in <module>
    dll = ctypes.CDLL(None)
  File "C:\Python36\lib\ctypes\__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

This is in following the basic getting started guide, and simply running `app.py`.

```py
# coding=utf-8
from kyoukai import Kyoukai
from kyoukai.asphalt import HTTPRequestContext

__author__ = "Gareth Coles"

app = Kyoukai("Mystic Minecraft")


@app.route("/")
async def index(ctx: HTTPRequestContext):
    return app.render_template("index.html")


if __name__ == "__main__":
    app.run()
```

**Comment by gdude2002** [comment]
I'm assuming this is some incompatibility with `async_generator` and Python 3.6, but I figured I'd check.

**Comment by SunDwarf** [comment]
Yes it is. I can't fix this myself. Raise it upstream at `async_generator`.

**Comment by gdude2002** [comment]
They appear to have solved the problem; it's actually an incompatibility with Windows.

They've pushed a fix to PyPi.
