### ISSUE TITLE
No clue what went wrong but it told me to report it

### ISSUE THREAD

**Issue by martmists** [SunDwarf/Kyoukai#8]
ERROR:asyncio:Exception in callback KyoukaiProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
    handle: <Handle KyoukaiProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
    Traceback (most recent call last):
      File "D:\Program_Files\Python\lib\asyncio\events.py", line 125, in _run
        self._callback(*self._args)
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\protocol.py", line 212, in connection_made
        self.ip, self.client_port = transport.get_extra_info("peername")
    ValueError: too many values to unpack (expected 2)
    INFO:Kyoukai:HTTP/1.1 GET / - 200
    WARNING:Kyoukai:Exception happened during HTTP parsing.
    WARNING:Kyoukai:This is not necessarily a bug.
    CRITICAL:Kyoukai:Unhandled exception inside Kyoukai, when processing a HTTP error!
    CRITICAL:Kyoukai:This is a bug. Please report it!
    CRITICAL:Kyoukai:Traceback (most recent call last):
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\protocol.py", line 202, in _wait
        await self.app.delegate_request(self, ctx)
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\app.py", line 552, in delegate_request
        protocol.handle_resp(response)
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\protocol.py", line 254, in handle_resp
        return self.write_response(response)
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\protocol.py", line 263, in write_response
        self.write(data)
      File "D:\Program_Files\Python\lib\site-packages\kyoukai\protocol.py", line 276, in write
        self._transport.write(data)
    AttributeError: 'NoneType' object has no attribute 'write'

**Comment by SunDwarf** [comment]
What the fuck did you fucking do

**Comment by martmists** [comment]
idk, I just let it run on localhost:80
